{"name": "Авторизацию с незаполненным обязательным полем", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 404. Actual: 504", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x000002795C498C50>, courier = ['qgycnrvkowhzqca', 'ovodvurgfamrgvb', 'kebvjuwzey'], data_flag = 0\n\n    @pytest.mark.parametrize(\"courier, data_flag\",\n                             [\n                                 (UserGenerator.register_new_courier_and_return_login_password(), 0),\n                                 (UserGenerator.register_new_courier_and_return_login_password(), 1)\n                              ]\n                             )\n    @allure.title(\"Авторизацию с незаполненным обязательным полем\")\n    @allure.description(\"Тест проверяет, что если хотя бы одно поле не заполнено, но авторизация не проходит\"\n                        \"Происходит проверка сообщения об ошибке\")\n    def test_courier_login_without_login_or_pwd(self, courier, data_flag):\n        data = Helper.set_data_with_none(courier, data_flag)\n    \n        response = requests.post(ApiUrl.LOGIN_API_URL, data=data)\n>       Assertions.assert_code_status(response, 404)\n\ntests\\test_courier_login.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [504]>, expected_status_code = 404\n\n    @staticmethod\n    @allure.step('Проверка статус-кода ответа')\n    def assert_code_status(response: Response, expected_status_code):\n>       assert response.status_code == expected_status_code, \\\n            f\"Unexpected status code! Expected: {expected_status_code}. Actual: {response.status_code}\"\nE       AssertionError: Unexpected status code! Expected: 404. Actual: 504\n\nhelpful_classes\\assertions.py:31: AssertionError"}, "description": "Тест проверяет, что если хотя бы одно поле не заполнено, но авторизация не проходитПроисходит проверка сообщения об ошибке", "steps": [{"name": "Создание для существующего курьера пары логин-пароль, в которой одно из полей пустое", "status": "passed", "parameters": [{"name": "courier", "value": "['qgycnrvkowhzqca', 'ovodvurgfamrgvb', 'kebvjuwzey']"}, {"name": "number", "value": "0"}], "start": 1710870531521, "stop": 1710870531521}, {"name": "Проверка статус-кода ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 404. Actual: 504\n", "trace": "  File \"C:\\trainings\\yandex_praktikum_git\\Sprint_7\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\trainings\\yandex_praktikum_git\\Sprint_7\\helpful_classes\\assertions.py\", line 31, in assert_code_status\n    assert response.status_code == expected_status_code, \\\n"}, "parameters": [{"name": "response", "value": "<Response [504]>"}, {"name": "expected_status_code", "value": "404"}], "start": 1710870591915, "stop": 1710870591915}], "parameters": [{"name": "courier", "value": "['qgycnrvkowhzqca', 'ovodvurgfamrgvb', 'kebvjuwzey']"}, {"name": "data_flag", "value": "0"}], "start": 1710870531521, "stop": 1710870591917, "uuid": "ba93ba83-9305-450b-81b4-ac9aec718112", "historyId": "0c6e90489a8ad5a118f71c55ff7eaf5e", "testCaseId": "f77123455ee03408ac884597cdb33755", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_without_login_or_pwd", "labels": [{"name": "epic", "value": "Логин курьера в системе"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "LAPTOP-IE2IJGHD"}, {"name": "thread", "value": "4124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}