{"name": "test_order_creation_success[GREY]", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 201. Actual: 500", "trace": "self = <tests.test_order_creation.TestOrderCreation object at 0x0000026D45054FB0>\norder = {'address': 'xgxdgemowj 52', 'comment': 'ryewwwbokfqmqnxqhmyl', 'deliveryDate': '2024-03-21', 'firstName': 'krdegwojofjtym', ...}, color = 'GREY'\n\n    @pytest.mark.parametrize(\"color\",\n                             [\n                                 \"BLACK\",\n                                 \"GREY\",\n                                 (\"BLACK\", \"GREY\"),\n                                 None\n                              ]\n                             )\n    def test_order_creation_success(self, order, color):\n        data = {\n            \"firstName\": order.get('first_name'),\n            \"lastName\": order.get('last_name'),\n            \"address\": order.get('address'),\n            \"metroStation\": order.get('metro_station'),\n            \"phone\": order.get('phone'),\n            \"rentTime\": order.get('rent_time'),\n            \"deliveryDate\": order.get('delivery_date'),\n            \"comment\": order.get('comment'),\n            \"color\": color\n        }\n    \n        response = requests.post(ApiUrl.CREATE_ORDER_API_URL, data=data)\n    \n>       Assertions.assert_code_status(response, 201)\n\ntests\\test_order_creation.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [500]>, expected_status_code = 201\n\n    @staticmethod\n    def assert_code_status(response: Response, expected_status_code):\n>       assert response.status_code == expected_status_code, \\\n            f\"Unexpected status code! Expected: {expected_status_code}. Actual: {response.status_code}\"\nE       AssertionError: Unexpected status code! Expected: 201. Actual: 500\n\nhelpful_classes\\assertions.py:46: AssertionError"}, "parameters": [{"name": "color", "value": "'GREY'"}], "start": 1710632458588, "stop": 1710632458941, "uuid": "273d7007-89ad-4cfe-b829-3e67f11b1293", "historyId": "67e88f5b2a3faf98ac14d6a63e484a6b", "testCaseId": "d5c9fef469675b1e7cbebc93fc01ef30", "fullName": "tests.test_order_creation.TestOrderCreation#test_order_creation_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_creation"}, {"name": "subSuite", "value": "TestOrderCreation"}, {"name": "host", "value": "LAPTOP-IE2IJGHD"}, {"name": "thread", "value": "2840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_creation"}]}